myproject/inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'inscripciones'

urlpatterns = [
    #path('', views.nueva_inscripcion),
    path('nueva-inscripcion', views.nueva_inscripcion, name='nueva-inscripcion'),
    
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about),
    #path('contact/', views.contact),
    path('cursos/', include('cursos.urls')),
    path('users/', include('users.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('correos/', include('correos.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

]

myproject/inscripciones/models.py
from django.db import models

# Create your models here.

class Inscripcion(models.Model):
    username = models.CharField(max_length=100, default='False')
    first_name = models.CharField(max_length=75)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    curso_inscripcion = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name
    

myproject/inscripciones/forms.py
from django import forms
from . import models


class CreateInscripcion(forms.ModelForm):
    class Meta:
        model = models.Inscripcion
        fields = ['username', 'first_name', 'last_name', 'email', 'curso_inscripcion']

myproject/inscripciones/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import forms

# Create your views here.
@login_required(login_url="/users/login/")
def nueva_inscripcion(request):
    if request.method == 'POST':
         form = forms.CreateInscripcion(request.POST)
         if form.is_valid():
              form.save()
              messages.success(request, "Tu subscripcion se procesó correctamente")
              return redirect("home")
    else:
        form = forms.CreateInscripcion()
    return render(request, 'inscripciones/nueva_inscripcion.html', {'form': form})

myproject/inscripciones/templates/inscripciones/nueva_inscripcion.html
{% extends 'layout.html' %}

{% block title %}
 Inscripciones
{% endblock  %}

{% block content %}
    <section>
        <div class="row">
            <div class="col-md-12 text-white">
                <h1>Inscripciones</h1>
            
                <form class="form-with-validation" action="{% url 'inscripciones:nueva-inscripcion' %} " method = "post">
                    {% csrf_token %}
                    <article class="text-white">
                        {{ form }}
                    </article>
                    <button class="form-submit">Suscribete</a></button>
                </form>
            </div>
        </div> 
    </section>
{% endblock  %}