myproject/correos/urls.py
from django.urls import path
from . import views

app_name = 'correos'

urlpatterns = [
    path('', views.contact, name="contact"),
    
    
]

myproject/cursos/urls.py
from django.urls import path
from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.cursos_list, name="list"),
    path('<slug:slug>', views.curso_page, name="page"),
    
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about),
    #path('contact/', views.contact),
    path('cursos/', include('cursos.urls')),
    path('users/', include('users.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('correos/', include('correos.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

]

myproject/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    Club de Literatura
{% endblock %}

{% block content %}
    <section class="quienes">
        <div class="container">

            <div class="row">
                <div class="col-md-12 margen-superior">
                    <div class="section-header text-center pb-5 "><br><br><br>
                        <h2 class="text-white titulo-club-2">Club de Literatura<span class="literatus">Literatus</span></h2>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center rockote">        
                        <p class="text-white parrafo-club">Nos reunimos por los cuatro puntos cardinales de la Ciudad de México; con la única intención de comentar algun libro. Las tertulias literarias son coordinadas por el asesor literartio de la zona; ya que él es quien tiene cierta autoridad en la materia y conocimientos profundos de la obra en turno. Se estructura un programa a seguir para abordar adecuadamente cada sesión. Se les hace llegar a los inscritos y a su correo electronico una minuta con los puntos a tocar de cada obra literaria. Dependiendo de esta misma se diseña el contenido de cada sesión(ya que cada texto tiene sus infinitas peculariedades a resaltar), para cubrir el ánalis total en no más de tres sesiones de máxino dos horas por sesión. Se invita a los participantes a tomar notas, con el objetivo de llevarse conocimientos que despues aprovecharan para el desarrollo de sus propios proyectos.
                        </p>
                        <h3 class="text-white parrafo-club">Importante: Inscribirse a las tertulias literarias es COMPLETAMENTE gratis. <br> Solamente se pide estar inscrito previamente en el Club de Literatura como único requisito. <br> Si aún no eres miembro de <span class="literatus-link">Literatus</span> te puedes inscribir <a href="{% url 'users:register' %}">aquí</a>
                        </h3>
                    
                        <div class="section-header text-center pb-5 contendor-proximas"><br>

                            <h2 class="proximas-tertulias text-white">Próximas TertuliasLiterarias:</h2>

                            <h2 class="text-white tertulia"><a class="linky" href="/cursos/cien-anios">Introspectiva a Cien años de soledad</a> <br><small class="small-indicaciones"><span>Lugar: Café La Cocina</span> C.d. Satelite, Zona Norte Ciudad de Mexico</small></h2>
                            <br>
                            <h2 class="text-white tertulia"><a class="linky" href="/cursos/cien-anios">Retro ánalisis de Pedro Páramo</a> <br><small class="small-indicaciones"><span>Lugar: Café La Cocina</span> C.d. Satelite, Zona Norte Ciudad de Mexico</small></h2>
                            <br>
                            <h2 class="text-white tertulia"><a class="linky" href="/cursos/cien-anios">Introspectiva a Cien años de soledad</a> <br><small class="small-indicaciones"><span>Lugar: Café La Morada</span> Col. Escandón, Zona centro Ciudad de Mexico</small></h2>
                        </div>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                    </div>
                </div>



            </div>

        </div>
    </section>
{% endblock %}

myproject/templates/contact.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block title %}
    Contac us
{% endblock %}

{% block content %}
    <section class="contact">

        <div class="container mb-3 mb-1g-5">
            
            <div class="row">
                <div class="col-md-12">
                    <div class="section-header text-center pb-2 pb-lg-5">
                        <h2>Contacto</h2>
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat ab expedita dolores. Vitae, architecto possimus! 
                        </p>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-center">
                <div class="col-12 col-md-12 col-lg-6 pt-4 pb-4">
                    <form action="#" class="bg-light p-4 m-auto shadow-sm">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <input class="form-control" placeholder="Nombre" type="text" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <input class="form-control" placeholder="Apellido" type="text" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <input class="form-control" placeholder="Email" type="email" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <textarea class="form-control" placeholder="Mensaje" rows="3" required></textarea>
                                </div>
                            </div>
                            <button class="btn btn-primary btn-lg btn-block mt-3" type="button"></button>    
                        </div>
                    
                    </form>

                </div>
                
            </div>

        </div>
        
    </section>
{% endblock %}

myproject/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}


{% block content %}
    <section class="quienes">
        <div class="container">

            <div class="row">
                <div class="col-md-12 margen-superior">
                    <div class="section-header text-center pb-5"><br><br><br>
                        <h2 class="text-white titulo-club">¿Quienes somos?</h2>
                        <p class="text-white titulo par-1"><span class="logo">Literatus</span>: <small>Club de literatura</small> <a href="/cursos/">Talleres y Cursos</a></p>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center rockote">

                <div class="col-12 col-md-12 col-lg-3 rock">
                    <div class="card bg-light shadow-sm border-0 px-2 py-3 mb-4 rockito">
                        <div class="text-center">
                            <img  class="foto" src="static/css/images/maria-5.jpg" alt="">
                        </div>
                        <div class="card-body">
                            <h3 class="card-title">Ana Bertha Castro</h3>
                            <h4 class="cargo-catedratico">Asesora literaria</h4>
                            <p class="parrafo-catedratico">
                                Egresada de la U.N.A.M. de la Licenciatura en Filosofía y Letras. 
                                Actualmente se desempeña cómo correctora de estilo en La Jormada. Ha participado
                                en diversos proyectos literarios de corte informativo para diferentes entidades en
                                la web. Así también se desempeñó como escritora de tiempo completo para la revista <strong>Algarabía</strong>
                                en la Ciudad de México. <br>
                                Impartirá en la modalidad de Club de Literatura, el taller:Una introspectiva a la ópera prima del autor colombiano Gabriel García Márquez, y dirigida a los conocedores de la grandiosa obra.<span class="enlaces"><a class="enlace" href="/cursos/cien-anios">Ánalisis de Cien años de soledad</a></span></p>
                            </p>
                            <a href="#" class="btn btn-secondary">Inscribirse</a>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-12 col-lg-3 rock">
                    <div class="card bg-light shadow-sm border-0 px-2 py-3 mb-4 rockito">
                        <div class="text-center">
                            <img src="static/css/images/maria-5.jpg" alt="">
                        </div>
                        <div class="card-body">
                            <h3 class="card-title">Ana Bertha Castro</h3>
                            <h4 class="cargo-catedratico">Asesora literaria</h4>
                            <p class="parrafo-catedratico">
                                Egresada de la U.N.A.M. de la Licenciatura en Filosofía y Letras. 
                                Actualmente se desempeña cómo correctora de estilo en La Jormada. Ha participado
                                en diversos proyectos literarios de corte informativo para diferentes entidades en
                                la web. Así también se desempeñó como escritora de tiempo completo para la revista <strong>Algarabía</strong>
                                en la Ciudad de México. <br>
                                Impartirá en la modalidad de Club de Literatura, el taller:Una introspectiva a la ópera prima del autor colombiano Gabriel García Márquez, y dirigida a los conocedores de la grandiosa obra.<span class="enlaces"><a class="enlace" href="/cursos/cien-anios">Ánalisis de Cien años de soledad</a></span></p> 
                            </p>
                            <a href="#" class="btn btn-secondary">Inscribirse</a>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-12 col-lg-3 rock">
                    <div class="card bg-light shadow-sm border-0 px-2 py-3 mb-4 rockito">
                        <div class="text-center">
                            <img src="static/css/images/maria-5.jpg" alt="">
                        </div>
                        <div class="card-body">
                            <h3 class="card-title">Ana Bertha Castro</h3>
                            <h4 class="cargo-catedratico">Asesora literaria</h4>
                            <p class="parrafo-catedratico">
                                Egresada de la U.N.A.M. de la Licenciatura en Filosofía y Letras. 
                                Actualmente se desempeña cómo correctora de estilo en La Jormada. Ha participado
                                en diversos proyectos literarios de corte informativo para diferentes entidades en
                                la web. Así también se desempeñó como escritora de tiempo completo para la revista <strong>Algarabía</strong>
                                en la Ciudad de México. <br>
                                Impartirá en la modalidad de Club de Literatura, el taller:Una introspectiva a la ópera prima del autor colombiano Gabriel García Márquez, y dirigida a los conocedores de la grandiosa obra.<span class="enlaces"><a class="enlace" href="/cursos/cien-anios">Ánalisis de Cien años de soledad</a></span></p>
                            </p>
                            <a href="#" class="btn btn-secondary">Inscribirse</a>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </section>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static '/css/js/main.js' %}" defer></script>
</head>
<body class="bg-dark p-2 justify-content-center">
    
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">


            <div class="container">
                <a href="#" class="navbar-brand"><span class="logo">Literatus</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbar-start" aria-controls="navbar-start" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                

                <div class="collapse navbar-collapse" id="navbar-start">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/about">Club Literario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cursos:list' %}">Cursos y Talleres</a>
                        </li>
                        
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'correos:contact' %}">Contacto</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %} ">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="col-md-3 offset-md-3 mensaje-alerta">
                {% if messages  %}
                    {% for message in  messages%}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                
                    {% endfor %}
                
                {% endif %}
            </div>   
        
        
        <main class="bg-dark p-3">
           
            {% block content %}
            
            
            {% endblock %}
        </main>
    </div>

    <footer class="bg-dark p-2 text-center">
        <div class="container">
            <p class="text-white">Todos los derechos reservados</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>