myproject/cursos/urls.py
from django.urls import path
from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.cursos_list, name="list"),
    path('<slug:slug>', views.curso_page, name="page"),
    
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about),
    #path('contact/', views.contact),
    path('cursos/', include('cursos.urls')),
    path('users/', include('users.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('correos/', include('correos.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

]

myproject/cursos/models.py
from django.db import models

# Create your models here.

class Curso(models.Model):
    title = models.CharField(max_length=100)
    banner = models.ImageField(default='fallback.png', blank=True)
    description = models.TextField()
    duracion_curso = models.DurationField(null=True)
    lugar_curso = models.TextField()
    fecha_de_inicio = models.DateTimeField(auto_now_add=False, auto_now=False, null=True)
    costo_del_curso = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.title

myproject/cursos/views.py
from django.shortcuts import render
from .models import Curso



# Create your views here.
def cursos_list(request):
    cursos = Curso.objects.all()
    return render(request, 'cursos/cursos_list.html', {'cursos': cursos})


def curso_page(request, slug):
    curso = Curso.objects.get(slug=slug)
    return render(request, 'cursos/curso_page.html', {'curso': curso})

myproject/cursos/templates/cursos/curso_page.html
{% extends 'layout.html' %}

{% block title %}
<h2>
    {{ curso.title }}
</h2>
{% endblock  %}

{% block content %}
    <section>
        
                <div class="container-main-page">
                    <div class="container-title">
                        <h1 class="text-white curso-title"> {{ curso.title }} </h1>
                    </div>
                    <div class="container-page">
                        <div class="container-image">
                            <img class="banner" 
                            src="{{ curso.banner.url }}" 
                            alt="{{ curso.title }}">
                        </div>
                            <p class="parrafo-page text-white"> <strong>Taller:</strong> {{ curso.description }} </p>
                            <p class="parrafo-page text-white"> <strong>Duración del curso:</strong> {{ curso.duracion_curso}} </p>
                            <p class="parrafo-page text-white"> <strong>Lugar:</strong> {{ curso.lugar_curso}} </p>
                            <p class="parrafo-page text-white"> <strong>Fecha de inicio:</strong> {{ curso.fecha_de_inicio}} </p>
                            <p class="parrafo-page text-white"> <strong>Costo del curso o taller:</strong> {{ curso.costo_del_curso}} </p><br>
                            <p class="parrafo-page text-white"></p>
                        </div>
                     </div>
                     <div class="boton-container">
                     <span class="boton-falso"><a class="boton_inscribirse-lectura" href="/inscripciones/nueva-inscripcion">Inscribirse</a></span>
                    </div>

    

</section>
{% endblock  %}

myproject/cursos/templates/cursos/cursos_list.html
{% extends 'layout.html' %}

{% block title %}
    Cursos
{% endblock  %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12 margen-superior">
                <h1 class="titulo-club text-white">Cursos y Talleres</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="section-header pb-5 ">
                    {% for curso in cursos  %}
                    <article class="post">
                     <h2 class="titulo-taller">
                     <a href="{% url 'cursos:page' slug=curso.slug %}">
                     {{ curso.title }}
                    </a>
                    </h2>
                    <p class="text-white parrafo-descripcion"><span class="campo">Taller:</span> {{ curso.description }} </p>
                <p class="text-white"><span class="campo" >Duración del curso:</span>  {{ curso.duracion_curso}} </p>
                <p class="text-white"><span class="campo" >Lugar:</span>  {{ curso.lugar_curso}} </p>
                <p class="text-white"><span class="campo" >Fecha de inicio:</span>  {{ curso.fecha_de_inicio}} </p>
                <p class="text-white"><span class="campo" >Costo del curso o taller:</span>  {{ curso.costo_del_curso}} </p><br>
                <p></p>
                </article>
                {% endfor %}
            </div>
        </div>
    </div>
    
    
        
    
    
</section>
{% endblock  %}